[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

upload_port = COM8
monitor_port = COM8

monitor_speed = 115200
upload_speed = 460800

lib_deps =
    adafruit/Adafruit GFX Library @ ^1.12.6
    adafruit/Adafruit SSD1306 @ ^2.5.17
    adafruit/Adafruit AHTX0 @ ^2.0.6